name = "ComputedFields"
uuid = "ca9a45ee-5845-4167-bbbe-6c434770cc9d"
authors = ["Stephan Kleinbölting <s.kleinboelting@gmail.com> and contributors"]
version = "0.2.0-DEV"

[deps]
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"

[compat]
julia = "1.6"
MacroTools = "0.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
